# workflows 이름
name: CI

# 해당 workflows 가 언제 실행될 것인지에 대한 트리거 지정
on:
  push:
    branches: [ main ] # main brance로 push 될 때 실행됨
  pull_request:
    branches" [ main ] # main branche로 pull request 될 때 실행됩니다.

# workflow 는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있음
jobs:
  build:
    name: CI
    # 해당 jobs 에서 아래의 steps 들이 어떠한 환경에서 실행될 것인지를 지정
    runs-on: ubuntu-latest

    steps: #순차적으로 명령어 수행
    # 작업에서 엑세스 할 수 있도록 $GITHUB_WORKSPACE 에서 저장소를 체크아웃
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'dingko'

    - name: Grant execute perssion for Maven
      run: chmod +x ./mvnw

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Get Current Time
      uses: 1466587594/get-current-tume@v2
      id: current-time
      with:
        format: YYYY-MM-DDTHH:mm:ss
        utcOffset: "+09:00" # 기준시가 UTC이므로 KST를 맞추기 위해 +9시간 추가

    - name: Print Current Time
      run: echo "Current Time=${{steps.current-time.outputs.formattedTime}}" # current-time 에서 지정한 포맷대로 현재 시간 출력
      shell: bash
